version: '3'
services:
  api:
    container_name: api
    build: .
    restart: always
    depends_on:
      - mongo
    image: cadastro-api
    command: npm start
    volumes:
      - ./dist:/api/dist
    ports:
      - "5050:5050"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:5.0.7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"